#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cd server

python manage.py migrate
python manage.py collectstatic --no-input
gunicorn -c gunicorn_config.py bot_constructor.wsgi:application --reload